version: '3.9'
volumes:
  db-store:
  php-fpm-socket:

services:
  composer:
    image: composer:1.8
    container_name: "todo-composer"
    volumes:
      - ./backend:/var/www
    working_dir: /var/www

  app:
    build: ./infrastructure/docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm:delegated
      - ./backend:/work:delegated
      - ./infrastructure/docker/php/bash/.bash_history:/root/.bash_history:delegated
      - ./infrastructure/docker/php/bash/psysh:/root/.config/psysh:delegated
    environment:
      TZ: Asia/Tokyo
      # Laravel environment
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  web:
    build: ./infrastructure/docker/nginx
    ports:
      - 8080:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm:delegated
      - ./backend:/work:delegated
    environment:
      TZ: Asia/Tokyo

  db:
    build: ./infrastructure/docker/mysql
    volumes:
      - db-store:/var/lib/mysql:delegated
    ports:
      - 33306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Tokyo

  fastapi:
    build:  ./infrastructure/docker/python
    volumes:
      - ./fastapi:/app    
    ports:
      - 8888:8000
    tty: true
    command: 'uvicorn main:app --reload --host 0.0.0.0'
    environment:
      TZ: Asia/Tokyo
      # FastAPI environment
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

